name: Docs

on:
  workflow_dispatch:  # allow to run manually
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        python_version: '3.11'
