# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
name: Upload Python Package

on:
  workflow_dispatch:  # allow to run manually
  release:
    types: [created]

    environment:
      name: pypi
      url: https://pypi.org/project/suitable

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package distributions
        run: python -m build -s -w

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
